// ./modules/abp.js
export const INIT_ABP_APPLICATION_CONFIGURATION = 'INIT_ABP_APPLICATION_CONFIGURATION';
export const SET_ABP_APPLICATION_CONFIGURATION = 'SET_ABP_APPLICATION_CONFIGURATION';

// ./modules/app.js
export const SET_PAGE_LOADING = 'SET_PAGE_LOADING';
export const SET_PROJECT_CONFIG = 'SET_PROJECT_CONFIG';
export const SET_PAGE_LOADING_ACTION = 'SET_PAGE_LOADING_ACTION';
export const RESET_APP_ALL_STATE = 'RESET_APP_ALL_STATE';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_MENU_SETTING = 'SET_MENU_SETTING';
export const SET_BEFORE_MINI_INFO = 'SET_BEFORE_MINI_INFO';

// ./modules/locale.js
export const INIT_LOCALE = 'INIT_LOCALE';
export const SET_LOCALLE_CONFIG = 'SET_LOCALLE_CONFIG';
export const SET_LOCALE = 'SET_LOCALE';

// ./modules/errorLog.js
export const ADD_ERROR_LOG_INFO = 'ADD_ERROR_LOG_INFO';
export const SET_ERROR_LOG_LIST_COUNT = 'SET_ERROR_LOG_LIST_COUNT';
export const ADD_AJAX_ERROR_INFO = 'ADD_AJAX_ERROR_INFO';

// ./modules/user.js
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_LAST_UPDATE_TIME = 'SET_LAST_UPDATE_TIME';
export const SET_SESSION_TIMEOUT = 'SET_SESSION_TIMEOUT';
export const AFTER_LOGIN_ACTION = 'AFTER_LOGIN_ACTION';
export const GET_USERINFO_ACTION = 'GET_USERINFO_ACTION';
export const RESET_USER_STATE = 'RESET_USER_STATE';
export const SET_ROLE_LIST = 'SET_ROLE_LIST';
export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION';
export const USER_LOGOUT_ACTION = 'USER_LOGOUT_ACTION';

// ./modules/permission.js
export const SET_DYNAMIC_ADDED_ROUTE = 'SET_DYNAMIC_ADDED_ROUTE';
export const BUILD_ROUTES_ACTION = 'BUILD_ROUTES_ACTION';
export const SET_FRONT_MENU_LIST = 'SET_FRONT_MENU_LIST';
export const SET_BACK_MENU_LIST = 'SET_BACK_MENU_LIST';
export const SET_LAST_BUILD_MENU_TIME = 'SET_LAST_BUILD_MENU_TIME';
export const RESET_PERMISSION_STATE = 'RESET_PERMISSION_STATE';
export const SET_PERM_CODE_LIST = 'SET_PERM_CODE_LIST';